# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param r response vector, 0 / 1
#' @param p prediction vector, 0 / 1
#' @noRd
#' @keywords Internal
tpr <- function(r, p) {
    .Call(`_rocmice_tpr`, r, p)
}

#' @param r response vector, 0 / 1
#' @param p prediction vector, 0 / 1
#' @noRd
#' @keywords Internal
fpr <- function(r, p) {
    .Call(`_rocmice_fpr`, r, p)
}

#' @param est vector of tpr or fpr
#' @param n number of positives in r or negatives in r
#' @noRd
#' @keywords Internal
var_prop <- function(est, n) {
    .Call(`_rocmice_var_prop`, est, n)
}

#' @param score NumericVector of scores
#' @param cutoff double, the cutoff
#' @noRd
#' @keywords Internal
cut_off <- function(score, cutoff) {
    .Call(`_rocmice_cut_off`, score, cutoff)
}

#' @param var NumericVector of variances
#' @param est NumericVector of proportions
#' @noRd
#' @keywords Internal
varlogit <- function(var, est) {
    .Call(`_rocmice_varlogit`, var, est)
}

#' Apply all possible cutoffs 
#' 
#' @param score the score
#' @param unique_vals the possible cutoffs
#' 
#' @return 
#' A matrix of dimensions length(score) x length(cutoffs)
#' 
#' @noRd
#' @keywords Internal
apply_cut_off <- function(score, unique_vals) {
    .Call(`_rocmice_apply_cut_off`, score, unique_vals)
}

#' Function to count number of val in x
#' @param x IntegerVector
#' @param val int, the value to count
#' @noRd
#' @keywords Internal
count_vals <- function(x, val) {
    .Call(`_rocmice_count_vals`, x, val)
}

#' Function to apply metrics
#'
#' @param m matrix with one column for each cutoff and one row for each 
#' value in score
#' @param r binary response vector
#' 
#' @return 
#' a list with 3 elements:
#' \item{tpri}{TPR values}
#' \item{fpri}{FPR values}
#' \item{vartpri}{variance for TPR}
#' @noRd
#' @keywords Internal
#'
apply_metrics <- function(m, r) {
    .Call(`_rocmice_apply_metrics`, m, r)
}

#' Equivalent to R rowMeans
#' @noRd
#' @keywords Internal
rcpp_rowMeans <- function(x) {
    .Call(`_rocmice_rcpp_rowMeans`, x)
}

#' Equivalent to R var
#' @noRd
#' @keywords Internal
rcpp_var <- function(samples) {
    .Call(`_rocmice_rcpp_var`, samples)
}

#' Apply var to matrix rows
#' @noRd
#' @keywords Internal
rowVars <- function(x) {
    .Call(`_rocmice_rowVars`, x)
}

#' @param est a matrix of (logit-transformed) proportion by imp
#' @param var a matrix of (logit transformed) variance by imp
#' @noRd
#' @keywords Internal
pool_rr_m <- function(est, var) {
    .Call(`_rocmice_pool_rr_m`, est, var)
}

